#include <QString>

QString idx_sass  = "body\n"
                    "    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif\n"
                    "    \n"
                    "    margin: 0\n"
                    "    padding: 0\n"
                    "    background-size: 100% 100%\n"
                    "\n"
                    "    user-select: none\n"
                    "    -webkit-user-select: none\n"
                    "    cursor: default\n"
                    "\n"
                    "::-webkit-scrollbar\n"
                    "    width: 10px\n"
                    "\n"
                    "::-webkit-scrollbar-track\n"
                    "    background: #f1f1f1\n"
                    "\n"
                    "::-webkit-scrollbar-track-dark\n"
                    "    background: #2E3440\n"
                    "\n"
                    "::-webkit-scrollbar-thumb\n"
                    "    background: #888\n"
                    "    border-radius: 8px\n"
                    "\n"
                    "::-webkit-scrollbar-thumb:hover\n"
                    "    background: #555\n"
                    "\n"
                    "img.background\n"
                    "    position: absolute\n"
                    "    \n"
                    "    width: 100%\n"
                    "    height: 100%\n"
                    "\n"
                    "#info\n"
                    "    position: absolute\n"
                    "    \n"
                    "    top: 196px\n"
                    "    left: 48px\n"
                    "\n"
                    "    width: 460px\n"
                    "    height: 352px\n"
                    "\n"
                    "    background-color: rgba(0, 0, 0, .65)\n"
                    "\n"
                    ".button\n"
                    "    border-radius: 8px\n"
                    "    background-color: #ffcb0b\n"
                    "    border: none\n"
                    "    cursor: pointer\n"
                    "\n"
                    ".button:hover:not([disabled])\n"
                    "    background-color: #fac60b\n"
                    "    box-shadow: 0 1px 8px 0 rgba(0, 0, 0, .2)\n"
                    "\n"
                    ".button:disabled\n"
                    "    background-color: rgba(0, 0, 0, .35)\n"
                    "    color: rgba(255, 255, 255, .7)\n"
                    "\n"
                    "    cursor: default\n"
                    "\n"
                    ".button-blue\n"
                    "    background-color: #8193c5\n"
                    "    color: white\n"
                    "\n"
                    ".button-blue:hover:not([disabled])\n"
                    "    background-color: #7284b6\n"
                    "\n"
                    "#launch, #pause\n"
                    "    position: absolute\n"
                    "\n"
                    "    width: 238px\n"
                    "    height: 64px\n"
                    "\n"
                    "    right: 128px\n"
                    "    bottom: 48px\n"
                    "\n"
                    "    font-size: 22px\n"
                    "\n"
                    "#pause\n"
                    "    display: none\n"
                    "\n"
                    "#predownload\n"
                    "    position: absolute\n"
                    "    display: none\n"
                    "\n"
                    "    width: 52px\n"
                    "    height: 52px\n"
                    "\n"
                    "    right: 386px\n"
                    "    bottom: 54px\n"
                    "\n"
                    "    border-radius: 32px\n"
                    "\n"
                    "    img\n"
                    "        width: 60%\n"
                    "        margin: auto\n"
                    "\n"
                    "#settings\n"
                    "    width: 76px\n"
                    "    height: 76px\n"
                    "\n"
                    "    position: absolute\n"
                    "\n"
                    "    right: 0\n"
                    "    bottom: 0\n"
                    "\n"
                    "    cursor: pointer\n"
                    "\n"
                    "    > img\n"
                    "        width: 40px\n"
                    "        height: 40px\n"
                    "        \n"
                    "        margin: 18px\n"
                    "\n"
                    "    .active\n"
                    "        display: none\n"
                    "\n"
                    "    .unactive\n"
                    "        display: block\n"
                    "\n"
                    "#settings.hovered\n"
                    "    .active\n"
                    "        display: block\n"
                    "\n"
                    "    .unactive\n"
                    "        display: none\n"
                    "\n"
                    ".downloader-panel\n"
                    "    user-select: none\n"
                    "\n"
                    "    .downloader-label\n"
                    "        position: absolute\n"
                    "\n"
                    "        left: 48px\n"
                    "        bottom: 100px\n"
                    "\n"
                    "        color: white\n"
                    "        font-size: 18px\n"
                    "\n"
                    "        #downloaded\n"
                    "            max-width: 720px\n"
                    "            display: inline-block\n"
                    "            word-break: break-all\n"
                    "\n"
                    "        #speed, #eta\n"
                    "            margin-left: 8px\n"
                    "            color: #cccccc\n"
                    "            font-weight: 100\n"
                    "\n"
                    "    .progress-bar\n"
                    "        position: absolute\n"
                    "\n"
                    "        padding: 0\n"
                    "\n"
                    "        left: 48px\n"
                    "        bottom: 52px\n"
                    "\n"
                    "        width: 720px\n"
                    "        height: 36px\n"
                    "\n"
                    "        background-color: rgba(0, 0, 0, .1)\n"
                    "        border: 1px solid rgba(0, 0, 0, .2)\n"
                    "        border-radius: 8px\n"
                    "\n"
                    "        .progress\n"
                    "            width: 0\n"
                    "            height: 100%\n"
                    "\n"
                    "            background-color: rgba(255, 255, 255, .7)\n"
                    "            border-radius: 6px\n"
                    "\n"
;