#include <string>

static const std::string QMLd = "import QtQuick 2.3\n"
                                "import QtQuick.Window 2.1\n"
                                "\n"
                                "Item {\n"
                                "    id: root\n"
                                "    width: 400\n"
                                "    height: propertyGrid.implicitHeight + 16\n"
                                "\n"
                                "    function orientationToString(o) {\n"
                                "        switch (o) {\n"
                                "        case Qt.PrimaryOrientation:\n"
                                "            return \"primary\";\n"
                                "        case Qt.PortraitOrientation:\n"
                                "            return \"portrait\";\n"
                                "        case Qt.LandscapeOrientation:\n"
                                "            return \"landscape\";\n"
                                "        case Qt.InvertedPortraitOrientation:\n"
                                "            return \"inverted portrait\";\n"
                                "        case Qt.InvertedLandscapeOrientation:\n"
                                "            return \"inverted landscape\";\n"
                                "        }\n"
                                "        return \"unknown\";\n"
                                "    }\n"
                                "\n"
                                "    Grid {\n"
                                "        id: propertyGrid\n"
                                "        columns: 2\n"
                                "        spacing: 8\n"
                                "        x: spacing\n"
                                "        y: spacing\n"
                                "\n"
                                "        Text {\n"
                                "            text: \"Screen \\\"\" + Screen.name + \"\\\":\"\n"
                                "            font.bold: true\n"
                                "        }\n"
                                "        Item { width: 1; height: 1 } // spacer\n"
                                "\n"
                                "        Text { text: \"dimensions\" }\n"
                                "        Text { text: Screen.width + \"x\" + Screen.height }\n"
                                "\n"
                                "        Text { text: \"pixel density\" }\n"
                                "        Text { text: Screen.pixelDensity.toFixed(2) + \" dots/mm (\" + (Screen.pixelDensity * 25.4).toFixed(2) + \" dots/inch)\" }\n"
                                "\n"
                                "        Text { text: \"logical pixel density\" }\n"
                                "        Text { text: Screen.logicalPixelDensity.toFixed(2) + \" dots/mm (\" + (Screen.logicalPixelDensity * 25.4).toFixed(2) + \" dots/inch)\" }\n"
                                "\n"
                                "        Text { text: \"device pixel ratio\" }\n"
                                "        Text { text: Screen.devicePixelRatio.toFixed(2) }\n"
                                "\n"
                                "        Text { text: \"available virtual desktop\" }\n"
                                "        Text { text: Screen.desktopAvailableWidth + \"x\" + Screen.desktopAvailableHeight }\n"
                                "\n"
                                "        Text { text: \"orientation\" }\n"
                                "        Text { text: orientationToString(Screen.orientation) + \" (\" + Screen.orientation + \")\" }\n"
                                "\n"
                                "        Text { text: \"primary orientation\" }\n"
                                "        Text { text: orientationToString(Screen.primaryOrientation) + \" (\" + Screen.primaryOrientation + \")\" }\n"
                                "    }\n"
                                "}";